<?php
    session_start();
    include "koneksi.php";

    $id_session = $_GET['id_session'] ?? 0;

    // Cek session dan ownership
    $session = mysqli_fetch_assoc(mysqli_query($koneksi, "SELECT * FROM quiz_session WHERE id_session='$id_session'"));
    if (! $session) {
        die("Session tidak ditemukan");
    }

    // Cek apakah user adalah owner session
    if ($session['id_user'] != $_SESSION['id_user']) {
        die("Hanya owner session yang bisa export hasil");
    }

    // Ambil data quiz
    $quiz = mysqli_fetch_assoc(mysqli_query($koneksi, "SELECT * FROM quiz WHERE id_quiz='{$session['id_quiz']}'"));

    // Ambil data peserta dengan nilai
    $peserta = mysqli_query($koneksi, "
    SELECT u.username, u.email, us.nilai, us.waktu_join
    FROM user_session us
    JOIN user u ON us.id_user = u.id_user
    WHERE us.id_session='$id_session'
    ORDER BY us.nilai DESC
");

    // Set headers untuk download Excel
    header("Content-Type: application/vnd.ms-excel");
    header("Content-Disposition: attachment; filename=\"Hasil_Quiz_{$quiz['judul']}_" . date('Y-m-d') . ".xls\"");
    header("Pragma: no-cache");
    header("Expires: 0");
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid black; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .title { font-size: 18px; font-weight: bold; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="title">Hasil Quiz:                                                                                                       <?php echo $quiz['judul']; ?></div>
    <div>Kode Session:                                                                   <?php echo $session['kode_session']; ?></div>
    <div>Tanggal Export:                                                                         <?php echo date('d/m/Y H:i'); ?></div>
    <br>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Username</th>
                <th>Email</th>
                <th>Nilai</th>
                <th>Status</th>
                <th>Waktu Bergabung</th>
            </tr>
        </thead>
        <tbody>
            <?php
                $no = 1;
                while ($row = mysqli_fetch_assoc($peserta)):
            ?>
            <tr>
                <td><?php echo $no++; ?></td>
                <td><?php echo htmlspecialchars($row['username']); ?></td>
                <td><?php echo htmlspecialchars($row['email']); ?></td>
                <td>
                    <?php
                        if ($row['nilai'] !== null) {
                            echo $row['nilai'];
                        } else {
                            echo 'Belum Mengerjakan';
                        }
                    ?>
                </td>
                <td>
                    <?php
                        if ($row['nilai'] !== null) {
                            echo 'Selesai';
                        } else {
                            echo 'Menunggu';
                        }
                    ?>
                </td>
                <td><?php echo date('d/m/Y H:i', strtotime($row['waktu_join'])); ?></td>
            </tr>
            <?php endwhile; ?>

            <?php if (mysqli_num_rows($peserta) == 0): ?>
            <tr>
                <td colspan="6" style="text-align: center;">Tidak ada peserta</td>
            </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <br>
    <div style="font-style: italic;">
        Generated by Cluezy TA -                                                                                                 <?php echo date('d/m/Y H:i'); ?>
    </div>
</body>
</html>